### ISSUE TITLE
Add a grid component instead of use bootstrap

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-material-ui#33]

**Comment by andrerpena** [comment]
As far as I know, the layout is defined by the Group component. The Bootstrap Group component uses BS layout but if you have your own Group, you can do whatever you want. I'm even thinking about creating an extension for RAF-BS for allowing draggable items. For that, all I'd have to do is to remove the BS grid system and start using this: https://github.com/STRML/react-grid-layout The only component I think I'd have to change is the Group

**Comment by JonatanSalas** [comment]
@andrerpena that's good! I will look on how use it.

**Comment by JonatanSalas** [comment]
@andrerpena For now I'm using bootstrap. Because of Bootstrap-ui. Then we both libraries are at the same state I will do this refactor. So for now I live this issue open.

**Comment by andrerpena** [comment]
Now that I'm reading this again it doesn't really make sense to use react-grid-layout. Sorry if I suggested that. If Material-UI doesn't come with a built-in grid system, an alternative would be to use http://flexboxgrid.com/ instead. The Grid is particularly important because of the components react to the `size` prop. I understand that using BS inside Material now makes sense as an intermediate state but after I'd remove it in favor of flexboxgrid. But this are just my 2 cents :smile:

**Comment by JonatanSalas** [comment]
I'm using a bootstrap customized version that only has the grid system. So, It doesn't affect the size of library. I will take a look to flexboxgrid.

**Comment by andrerpena** [comment]
Ok. That makes sense. If you want to keep it using BS it's your choice. I just think it a little weird conceptually as BS and MUI are competitors. It's like using jQuery in a React project. But I do understand you're only using the Grid system. Do as you wish.

**Comment by JonatanSalas** [comment]
I will keep using for now bootstrap because the project it's in advance. But then when this is stable I will take a look to flexboxgrid

**Comment by andrerpena** [comment]
Perfect

**Comment by JonatanSalas** [comment]
@andrerpena I have decided to use bootstrap-grid css because I can use it to implement the same functionality that bootstrap provides.

**Comment by andrerpena** [comment]
Great!
